import Head from "next/head";
import React, { Fragment, ReactNode } from "react";
import { useDispatch, useSelector } from "react-redux";
import { increment, incrementByAmount } from "../features/counter/counterSlice";
import { RootState } from "../store/store";

type LayoutProps = {
  children: ReactNode;
};

const Layout = ({ children }: LayoutProps) => {
  const count = useSelector((state: RootState) => state.counter.value);
  const dispatch = useDispatch();
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {count}
      <br />
      <button onClick={() => dispatch(increment())}>클릭1</button>
      <button onClick={() => dispatch(incrementByAmount(10))}>클릭2</button>
      {children}
    </Fragment>
  );
};

export default Layout;
